CREATE TABLE A2O_RIGHT
(
  RI_ID         INTEGER      PRIMARY KEY,
  RI_NAME       VARCHAR (20) NOT NULL,
  RI_SCOPE      VARCHAR (20) NOT NULL,
  RI_RIGHT      VARCHAR (1)  NOT NULL
);

CREATE TABLE A2O_ROLE
(
  RO_ID    INTEGER      PRIMARY KEY,
  RO_NAME  VARCHAR (20) NOT NULL
);

CREATE TABLE A2O_USER
(
  U_ID            INTEGER       PRIMARY KEY,
  U_NAME          VARCHAR (50)  NOT NULL,
  U_EMAIL         VARCHAR (80)  NOT NULL,
  U_FIRST_NAME    VARCHAR (50)  NOT NULL,
  U_LAST_NAME     VARCHAR (50)  NOT NULL,
  U_PASSWORD      VARCHAR (200) NOT NULL,
  U_SALT          VARCHAR (40)  NOT NULL
);

CREATE TABLE A2O_ROLERIGHT
(
  RR_RO_ID  INTEGER NOT NULL,
  RR_RI_ID  INTEGER NOT NULL
);


CREATE TABLE A2O_USERROLE
(
  UR_U_ID   INTEGER NOT NULL,
  UR_RO_ID  INTEGER NOT NULL
);

CREATE TABLE A2O_ACCESS_TOKEN ( 
  AT_ID             INTEGER         PRIMARY KEY,
  AT_ACCESS_TOKEN 	VARCHAR (255)	NOT NULL,
  AT_TOKEN_TYPE 	VARCHAR (10)	NOT NULL,
  AT_EXPIRES_IN 	INTEGER			NOT NULL,
  AT_REFRESH_TOKEN 	VARCHAR (255)	NOT NULL,
  AT_SESSION_ID 	VARCHAR (255)	NOT NULL,
  AT_CREATED_AT 	TIMESTAMP       NOT NULL,
  AT_USER           VARCHAR (50)    NOT NULL
);
